# Generated by Django 2.1 on 2019-05-30 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_description',
            new_name='description',
        ),
    ]
