# Generated by Django 2.1 on 2019-05-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20190530_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='url',
        ),
    ]
